# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go test & Docker build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create config.yaml for testing
      run: |
        echo "your_key: ${{secrets.TEST_CONFIG}}" > ./pkg/config/config.yaml

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{secrets.ACR_NAMESPACE}}.azurecr.io
        username: ${{secrets.ACR_USERNAME}}
        password: ${{secrets.ACR_PASSWORD}}

    - name: Build order-processing image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./cmd/order-processing/Dockerfile
        push: true
        tags: ${{secrets.ACR_NAMESPACE}}.azurecr.io/order-processing:latest